Update v5-0-26-to-v5-0-41.md
In the Add Serenity.Extensions Package Reference of https://serenity.is/docs/migration/v5-0-26-to-v5-0-41 a call to services.AddExcelExporter() was missing, causing an error

InvalidOperationException: Unable to resolve service for type 'Serenity.Reporting.IDataReportExcelRenderer' while attempting to activate 'Serenity.Extensions.Pages.ReportController'.